use biome.js

diff --git a/.github/workflows/lint-and-format.yml b/.github/workflows/lint-and-format.yml
--- a/.github/workflows/lint-and-format.yml
+++ b/.github/workflows/lint-and-format.yml
@@ -8,6 +8,8 @@ on:
 jobs:
   lint-and-format:
     runs-on: ubuntu-slim
+    env:
+      BIOME: ${{ github.event_name == 'pull_request' && 'ci' || 'check --write' }}
     steps:
       - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
       - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
@@ -20,7 +22,7 @@ jobs:
         run: |
           set -x
           pnpm install --frozen-lockfile
-          pnpm eslint . --fix
+          pnpm biome $BIOME --reporter=default --reporter=github | sed "s|,file=|,file=backend/|g" || echo "BIOME_FAILED=1" >> "$GITHUB_ENV"
       - uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
         if: ${{ github.event_name != 'pull_request' }}
         with:
@@ -30,3 +32,9 @@ jobs:
           branch: lint-and-format
           title: lint-and-format
           body: lint-and-format
+      - name: diff
+        if: ${{ github.event_name == 'pull_request' }}
+        run: git diff --exit-code
+      - name: biome
+        if: ${{ env.BIOME_FAILED == '1' }}
+        run: exit 1
